version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'gradle'
    directories:
      - '/android/'
      - '/example/android/'
    schedule:
      interval: 'monthly'
    labels:
      - 'nitro-core'
      - 'nitrogen'
      - 'dependencies'
      - 'kotlin'

  - package-ecosystem: 'bundler'
    directory: '/example/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'ruby'

  - package-ecosystem: 'npm'
    directories:
      - '/example/'
      - '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'nitro-core'
      - 'dependencies'
      - 'typescript'
      - 'nitrogen'

    groups:
      react-native-cli:
        patterns:
          - '@react-native-community/cli*'
      babel:
        patterns:
          - '@babel/*'
      react-native:
        patterns:
          - 'react'
          - 'react-native'
          - '@react-native/*'
          - 'react-native-builder-bob'
      nitro:
        patterns:
          - 'nitrogen'
          - 'react-native-nitro-modules'
