name: Test C++ Code
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unittest.yml'
      - 'cpp/**'
  pull_request:
    paths:
      - '.github/workflows/unittest.yml'
      - 'cpp/**'
  workflow_dispatch:

jobs:
  test_cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang-tidy pkg-config python3 git
          sudo apt-get install -y libgtest-dev libopus-dev libx264-dev libx265-dev libnuma-dev

      - name: Cache 3rdparty output
        id: cache-3rdparty-unittest
        uses: actions/cache@v4
        with:
          path: 3rdparty/output
          key: ${{ runner.os }}-3rdparty-unittest-${{ hashFiles('3rdparty/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-3rdparty-unittest-

      - name: Download 3rdparty artifacts
        if: steps.cache-3rdparty-unittest.outputs.cache-hit != 'true'
        run: cd 3rdparty && ./download.sh

      - name: build 3rdparty
        if: steps.cache-3rdparty-unittest.outputs.cache-hit != 'true'
        run: cd 3rdparty && ./build_unittest.sh

      - name: Build C++ tests
        run: |
          cd cpp/__tests__
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Run C++ tests
        run: cd cpp/__tests__/build && ./testcpp --gtest_output=xml:report.xml

      - name: Show test report in logs
        run: cat cpp/__tests__/build/report.xml

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'cpp/__tests__/build/report.xml'
